In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [80]:
Q = Qobj(np.random.rand(4, 4))

I = qeye(Q.shape[0])
a = destroy(Q.shape[0])
Ham = a.dag() * a + 1/2

d = displace(Q.shape[0], 1j)
s = squeeze(Q.shape[0], 0.25 + 0.25j)
vac = basis(Q.shape[0], 0)
dm = fock_dm(Q.shape[0])
co_dm = coherent_dm(Q.shape[0], 1.25)
print(co_dm)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.20735725 0.26714583 0.20703558 0.22389639]
 [0.26714583 0.34417363 0.26673142 0.28845381]
 [0.20703558 0.26673142 0.20671441 0.22354906]
 [0.22389639 0.28845381 0.22354906 0.24175472]]
